Modified db
TacheRadu/Morse pull request #23
Opened 2021-04-23 07:16 UTC by LauraMalinaBenchea

Modifed the database in the App class. It now contains two tables:

Channels table with the columns channel_id and channel_name;
User table with the columns :channel_id (foreign key from channels), username and password
Also modifed the method which inserts an entry into the DB and added the removeUser() method which should delete an entry from the user table and cascade to channels table

2021-04-23 07:45 UTC, HristeaIonut approved these changes

2021-04-24 08:12 UTC, TacheRadu requested changes

2021-04-24 08:12 UTC, TacheRadu commented on app/src/main/java/com/morse/App.java
> +        String remove = "DELETE FROM users WHERE lower(trim(username)) = lower(trim(?)); ";
The user name is case sensitive

2021-04-24 08:12 UTC, TacheRadu commented on app/src/main/java/com/morse/App.java
> +                + "	channel_name text NOT NULL\n"
Drop the channel_

2021-04-24 08:22 UTC, TacheRadu approved these changes

2021-04-24 08:22 UTC, merged